# Generated by Django 6.1 on 2026-08-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('thumbnail_url', models.ImageField(upload_to='thumbnails/')),
                ('video', models.FileField(upload_to='videos/originals/')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
