# Generated by Django 6.1 on 2026-08-31 17:51

import videos_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.ImageField(upload_to=videos_app.utils.thumbnail_upload_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to=videos_app.utils.video_upload_path),
        ),
    ]
