# Generated by Django 6.1 on 2026-08-31 18:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0002_alter_video_thumbnail_url_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
