# Generated by Django 6.1 on 2026-09-02 23:37

import videos_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0003_video_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.ImageField(blank=True, upload_to=videos_app.utils.thumbnail_upload_path),
        ),
    ]
