# Generated by Django 6.1 on 2026-09-03 01:14

import videos_app.utils
import videos_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0004_video_is_processed_alter_video_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.ImageField(blank=True, upload_to=videos_app.utils.thumbnail_upload_path, validators=[videos_app.validators.validate_thumbnail_file_extension]),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to=videos_app.utils.video_upload_path, validators=[videos_app.validators.validate_video_file_extension]),
        ),
    ]
