# Generated by Django 6.1 on 2026-09-03 14:16

import videos_app.utils
import videos_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_app', '0005_alter_video_thumbnail_url_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.ImageField(upload_to=videos_app.utils.thumbnail_upload_path, validators=[videos_app.validators.validate_thumbnail_file_extension]),
        ),
    ]
